In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk',
         'the glass of juice',
         'the cup of tea',
         'I am a good boy',
         'I am a good developer',
         'understand the meaning of words',
         'your videos are good']

In [3]:
sent 

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
##Defining the vocabulary size
voc_size = 10000

In [6]:
one_hot_repr= [one_hot(words,voc_size)for words in sent] 
one_hot_repr


[[7878, 5545, 6856, 8642],
 [7878, 5545, 6856, 5392],
 [7878, 8202, 6856, 16],
 [7037, 2893, 6174, 9613, 2883],
 [7037, 2893, 6174, 9613, 9544],
 [5747, 7878, 2969, 6856, 7787],
 [1892, 5711, 7414, 9613]]

In [10]:
##word embedding Representation

from tensorflow.keras.layers import Embedding 
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences 

In [11]:
import numpy as np

In [13]:
sent_length=8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)

In [14]:
embedded_docs

array([[   0,    0,    0,    0, 7878, 5545, 6856, 8642],
       [   0,    0,    0,    0, 7878, 5545, 6856, 5392],
       [   0,    0,    0,    0, 7878, 8202, 6856,   16],
       [   0,    0,    0, 7037, 2893, 6174, 9613, 2883],
       [   0,    0,    0, 7037, 2893, 6174, 9613, 9544],
       [   0,    0,    0, 5747, 7878, 2969, 6856, 7787],
       [   0,    0,    0,    0, 1892, 5711, 7414, 9613]], dtype=int32)

In [18]:
##feature representation
dim=10
voc_size = 10000
sent_length=8

In [24]:
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_length=sent_length))
model.compile(optimizer='adam',loss='mse')

/home/adwait/anaconda3/envs/ml-env/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [28]:
model.build()
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
from keras.models import Sequential
from keras.layers import Embedding

voc_size = 10000
sent_length = 8
dim = 10

model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')

model.build(input_shape=(None, sent_length))  # 👈 Add this line
model.summary()


/home/adwait/anaconda3/envs/ml-env/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [34]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


array([[[ 0.0368922 , -0.01563405,  0.03348893,  0.00679849,
          0.04804474, -0.03072928,  0.04009057, -0.03594692,
         -0.03595371, -0.00259978],
        [ 0.0368922 , -0.01563405,  0.03348893,  0.00679849,
          0.04804474, -0.03072928,  0.04009057, -0.03594692,
         -0.03595371, -0.00259978],
        [ 0.0368922 , -0.01563405,  0.03348893,  0.00679849,
          0.04804474, -0.03072928,  0.04009057, -0.03594692,
         -0.03595371, -0.00259978],
        [ 0.0368922 , -0.01563405,  0.03348893,  0.00679849,
          0.04804474, -0.03072928,  0.04009057, -0.03594692,
         -0.03595371, -0.00259978],
        [ 0.02141911, -0.00860053,  0.01343649, -0.01321504,
          0.04868761, -0.04508984, -0.03090769,  0.04221033,
         -0.03535239,  0.03636828],
        [ 0.03174071,  0.03738989,  0.01910364, -0.00905437,
          0.00653889, -0.02670186,  0.02685453,  0.03736421,
          0.04846377, -0.00555839],
        [-0.03958293,  0.04603299, -0.00577984, -0.0

In [32]:
embedded_docs[0]

array([   0,    0,    0,    0, 7878, 5545, 6856, 8642], dtype=int32)